/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function fibonacci(n: number): string

export declare function guessingGame(): void

export declare function helloNapi(input?: string | undefined | null): string
